# Tcl package index file
# This file is NOT generated by the "pkg_mkIndex" command 

set _name    Exp
set _version 1.0
set _files   {sweeper timeplot statusbar read_conf fit_res manual_db\
              monitor dataconvs widgets temp_curve widget_ac_source widget_sweep}

set _pcmd {}
foreach _f $_files { lappend _pcmd "source [file join $dir $_f.tcl]" }
lappend _pcmd "package provide $_name $_version"
package ifneeded $_name $_version [join $_pcmd \n]

