#!/usr/bin/perl
use strict;
use warnings;
use JSON;

my $prog = $0;
$prog =~s|^.*/([^/]*$)|$1|;

############################################################
############################################################
# Extract nmr data from a file
#

############################################################
my $sigs;
my $types;

# first pass:
#  - read signal information
#  - convert time to freq.shift
#  - scale x2, x3 peaks, remove numbers from names
#  - for each peak type (name + exc + grad)
#    find min and max peak length in frequency
#    (we assume that longer peaks are better for fitting)
#  - fit peaks with f^2 = a(df-df0).

foreach my $sig (@ARGV) {

  # read inf file for the signal
  my $inf = $sig; $inf=~s/\.sigf?$//; $inf.='.inf';
  `sig_get_info $sig` unless -f $inf;
  open INF, "$inf" or die "can't open file: $inf: $!\n";
  $sigs->{$sig}->{pars} = decode_json(join "\n", (<INF>));
  close INF;

  my $pars = $sigs->{$sig}->{pars};
  for (my $i = 0; $i <= $#{$pars->{sfft_t}}; $i++){
    printf "%f %e %e %e\n",
      ${$pars->{sfft_t}}[$i],
      ${$pars->{sfft_x}}[$i],
      ${$pars->{sfft_y}}[$i],
      ${$pars->{sfft_a}}[$i];
  }
  printf "\n";

}






